import os

translations = {
    # dashboard
    "Global Dashboard": "Tableau de Bord Global",
    "Real-time intelligence for the 2024 Harvest Season.": "Informations en temps réel pour la saison de récolte 2024.",
    "Oct 12 - Nov 28": "12 Oct - 28 Nov",
    "Total Harvests": "Récoltes Totales",
    ">Tons<": ">Tonnes<",
    "Avg. Maturity": "Maturité Moyenne",
    ">Optimal<": ">Optimale<",
    "Active Alerts": "Alertes Actives",
    "Attention!": "Attention !",
    "Resource Usage": "Utilisation des Ressources",
    "92% Cap": "Capacité 92%",
    ">Units<": ">Unités<",
    "Harvest Performance Over Time": "Performance de Récolte au Fil du Temps",
    "<span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span>": "<span>Lun</span><span>Mar</span><span>Mer</span><span>Jeu</span><span>Ven</span><span>Sam</span><span>Dim</span>",
    "Estate Spotlight": "Lumière sur le Domaine",
    "Northern Slope Sector A": "Pente Nord Secteur A",
    "Soil pH Level": "Niveaux pH du Sol",
    "Moisture Content": "Taux d'Humidité",
    "View Satellite map": "Voir la carte satellite",
    "Recent Harvest Activity": "Activité de Récolte Récente",
    "New harvest logged - Sector B-12": "Nouvelle récolte enregistrée - Secteur B-12",
    "Premium Chemlali Variety": "Variété Premium Chemlali",
    "14 mins ago": "Il y a 14 min",
    "Soil analysis completed": "Analyse du sol terminée",
    "Sector D-04 • pH stabilized": "Secteur D-04 • pH stabilisé",
    "2 hours ago": "Il y a 2 heures",
    "Resource Fleet": "Flotte de Ressources",
    "Current deployment status.": "Statut de déploiement actuel.",
    "Mechanical Harvesters": "Moissonneuses Mécaniques",
    "Transport Trucks": "Camions de Transport",
    "Top 5% regional organic standards.": "Top 5% des normes biologiques régionales.",
    
    # auth
    "The Curated Harvest": "La Récolte d'Exception",
    "Welcome back": "Bon retour",
    "Log in to manage your olive estate operations.": "Connectez-vous pour gérer les opérations de votre domaine oléicole.",
    "Email Address": "Adresse e-mail",
    "Password": "Mot de passe",
    "loading ? 'Signing in...' : 'Sign in to Estate'": "loading ? 'Connexion en cours...' : 'Se connecter'",
    "OR ACCESS VIA": "OU ACCÉDER VIA",
    "Continue with Google": "Continuer avec Google",
    "New to the Harvest?": "Nouveau sur la plateforme ?",
    "Already have an account?": "Vous avez déjà un compte ?",
    "Create an account": "Créer un compte",
    "Login": "Se connecter",
    "Heritage meets Tech": "L'Héritage rencontre la Technologie",
    "Empowering the legacy through precision.": "Renforcer l'héritage par la précision.",
    "Real-time yield analytics and soil intelligence for the modern Tunisian olive estate.": "Analyses de rendement en temps réel et intelligence des sols pour le domaine oléicole tunisien moderne.",
    "Join the elite network of Tunisian olive producers.": "Rejoignez le réseau d'élite des producteurs d'olives tunisiens.",
    "Full Name": "Nom Complet",
    "Cooperative Role": "Rôle Coopératif",
    "loading ? 'Creating account...' : 'Complete Registration'": "loading ? 'Création de compte...' : 'Terminer l\\'inscription'",
    "OR CREATE VIA": "OU CRÉER VIA",
    "Create with Google": "Créer avec Google",
    "Preserving the legacy through precision.": "Préserver l'héritage par la précision.",
    "Empowering Tunisian estates with real-time yield analytics, soil intelligence, and historical harvest archiving for the modern age.": "Renforcer les domaines tunisiens avec des analyses de rendement en temps réel, une intelligence des sols et un archivage historique pour l'ère moderne.",
    
    # user management & profile
    "Cooperative Workforce": "Effectif Coopératif",
    "Administrative hub for managing account permissions, roles, and access credentials across the Olivia ecosystem.": "Centre administratif pour gérer les permissions, rôles et identifiants d'accès dans l'écosystème Olivia.",
    "Cancel Registration": "Annuler l'inscription",
    "Onboard New User": "Intégrer un Nouvel Utilisateur",
    "User Onboarding": "Intégration d'un Utilisateur",
    "Full Identity Name": "Nom et Prénom",
    "Official Email": "Email Officiel",
    "Initial Credentials": "Mot de passe initial",
    "Assigned Role": "Rôle Assigné",
    "loading ? 'Onboarding...' : 'Register Account'": "loading ? 'Intégration...' : 'Créer le compte'",
    "User Details": "Détails de l'Utilisateur",
    "System Role": "Rôle Système",
    "Status Control": "Contrôle du Statut",
    "Reference": "Référence",
    "Active": "Actif",
    "Banned": "Banni",
    "Querying Digital Records...": "Interrogation des Registres...",
    "No administrative records found.": "Aucun registre administratif trouvé.",
    "Profile Management": "Gestion du Profil",
    "Update your digital identity and harvest credentials.": "Mettez à jour votre identité numérique et vos identifiants.",
    "Terminate Session": "Se Déconnecter",
    "Activity Index": "Indice d'Activité",
    "Harvest Tasks": "Tâches de Récolte",
    "Soil Scans": "Scans du Sol",
    "Identification Data": "Données d'Identification",
    "Official Email Address": "Adresse Email Officielle",
    "Current User Role": "Rôle Utilisateur Actuel",
    "Entity Reference ID": "ID de Référence d'Entité",
    "Enter your full name": "Entrez votre nom complet",
    "updating ? 'Synchronizing...' : 'Commit Changes'": "updating ? 'Synchronisation...' : 'Appliquer les Modifications'",
    "Security Suite": "Suite de Sécurité",
    "Rotate passwords and manage 2FA keys.": "Changez vos mots de passe et gérez la sécurité active.",
    "Alert Rules": "Règles d'Alerte",
    "Fine-tune your harvest threshold alerts.": "Affinez vos alertes de seuils de récolte.",

    # verger management
    "Estate Registry": "Registre du Domaine",
    "Orchard Management": "Gestion des Vergers",
    "Strategize and manage your localized olive assets across the estate.": "Gérez et planifiez vos actifs oléicoles localisés sur le domaine.",
    "Cancel Operation": "Annuler l'Opération",
    "Register New Sector": "Enregistrer un Secteur",
    "Modification Protocol": "Protocole de Modification",
    "Initial Registry Protocol": "Protocole d'Enregistrement",
    "Orchard Nomenclature": "Nomenclature du Verger",
    "e.g. North Sector B-12": "ex. Secteur Nord B-12",
    "Olive Taxonomy": "Taxonomie des Olives",
    "Woirkforce Quota (Trees)": "Quota de Main-d'œuvre (Arbres)",
    "Legal Proprietor": "Propriétaire Légal",
    "Select Oleiculteur": "Sélectionner Oléiculteur",
    "Operational Lead": "Responsable Opérationnel",
    "Assign Chef d'Équipe": "Assigner Chef d'Équipe",
    "Telemetry Origin (GPS)": "Localisation GPS",
    "Map click or GPS...": "Clic sur carte ou GPS...",
    "Discard Registry": "Ignorer l'Enregistrement",
    "Confirm Transformation": "Confirmer la Modification",
    "Authorize Sector Registry": "Autoriser l'Enregistrement",
    "Search by name, location, olive type, or lead...": "Rechercher par nom, emplacement, type d'olive...",
    "Catalog Size:": "Taille du Catalogue :",
    "Sectors": "Secteurs",
    "Estate Identification": "Identification du Domaine",
    "Maturity Progress": "Progression de Maturité",
    "Workforce Context": "Contexte Opérationnel",
    "Operational Stage": "Étape Opérationnelle",
    "Actions": "Actions",
    "GPS Active": "GPS Actif",
    "Readiness": "Préparation",
    "View Team Lead Report": "Voir le Rapport du Responsable",
    "Page {{ currentPage }} of {{ totalPages }}": "Page {{ currentPage }} sur {{ totalPages }}",
    "Estate Telemetry Radar": "Radar de Télémétrie du Domaine",
    "Intelligence Stream": "Flux d'Intelligence",
    "Reported by:": "Rapporté par :",
    "Maturity Analysis": "Analyse de Maturité",
    "Field Notes": "Notes de Terrain",
    "No field observations provided.": "Aucune observation de terrain fournie.",
    "Optical Evidence": "Preuve Optique",
    "Dismiss Report": "Fermer le Rapport",
}

directory = r"c:\PIITWM\Sem2\Projet\Projet\frontend\src\app"

for root, _, files in os.walk(directory):
    for file in files:
        if file.endswith(".html"):
            path = os.path.join(root, file)
            with open(path, "r", encoding="utf-8") as f:
                content = f.read()
            
            original_content = content
            for en, fr in translations.items():
                content = content.replace(en, fr)
            
            if original_content != content:
                with open(path, "w", encoding="utf-8") as f:
                    f.write(content)
                print(f"Updated {file}")
