spring.application.name=backend
# Au lieu de mettre la clé ici, on donne le chemin du fichier
firebase.config.path=classpath:firebase-Key.json
# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=olivoocom@gmail.com
spring.mail.password=johbyysrkveydypd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Multipart Upload Configuration (for Chat Images)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
